### GENERAL SETTINGS ###

# Site settings
title: "MOBILE AUTOMATORS"
description: "Mobile test automation community"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: http://mobileautomators.com

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#ff6b6b"
  primary_rgb: "0,179,254" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#345770"
  link: "#4ecdc4"
  link_hover: "#4ecdc4"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  nav: "#354754"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
links:
  - title: The Meetup page
    url: http://meetup.com/Mobile-Automators-Israel/
  - title: Our YouTube channel
    url: https://www.youtube.com/channel/UCBHV7BBUEZkoS8IkEk9PcsQ/videos
  - title: GitHub page
    url: https://github.com/MobileAutomators

# Members information. Shown on About page.
members:
  - name: Ran Byron
    position: "Automation & Tools Lead at EverythingMe"
    text: Yeah... it's just me.
    img: ranbena.jpg
    social:
      - title: envelope #use for email address
        url: mailto:ran@ranbena.com
      - title: twitter
        url: http://twitter.com/ranbena
      - title: tumblr
        url: http://ranbena.com
